site_name: Nexus HTTP Server Documentation
site_url: https://thenexusavenger.github.io/Nexus-Http-Server
repo_name: TheNexusAvenger/Nexus-Http-Server
repo_url: https://github.com/TheNexusAvenger/Nexus-Http-Server

theme:
  name: 'material'
  palette:
    primary: 'Blue'
    accent: 'Light Blue'

nav:
  - Home: index.md
  - Getting Started:
    - Standard Server: getting-started/standard-server.md
    - Split Requests: getting-started/split-requests.md

markdown_extensions:
  - admonition
  - codehilite